### ISSUE TITLE
curator latest container with start problems

### ISSUE THREAD

**Issue by vorti2** [bobrik/docker-curator#27]
Hi,
the `latest` version of the docker container in our kubernetes 1.7.2 cluster has the following start problems:
```
Traceback (most recent call last):
  File "/usr/bin/curator", line 7, in <module>
    import urllib3.contrib.pyopenssl
  File "/usr/lib/python2.7/site-packages/urllib3/contrib/pyopenssl.py", line 46, in <module>
    import OpenSSL.SSL
  File "/usr/lib/python2.7/site-packages/OpenSSL/__init__.py", line 8, in <module>
    from OpenSSL import rand, crypto, SSL
  File "/usr/lib/python2.7/site-packages/OpenSSL/rand.py", line 12, in <module>
    from OpenSSL._util import (
  File "/usr/lib/python2.7/site-packages/OpenSSL/_util.py", line 6, in <module>
    from cryptography.hazmat.bindings.openssl.binding import Binding
  File "/usr/lib/python2.7/site-packages/cryptography/hazmat/bindings/openssl/binding.py", line 13, in <module>
    from cryptography.hazmat.bindings._openssl import ffi, lib
ImportError: Error loading shared library libssl.so.1.0.0: No such file or directory (needed by /usr/lib/python2.7/site-packages/cryptography/hazmat/bindings/_openssl.so)
```
With the version `5.4.0` curator starts with no problems.

CU
Wilhelm

**Comment by jasonyihk** [comment]
same issue here. only happens to latest. not related to kubernetes version.

**Comment by bobrik** [comment]
I reverted #22, it should be back to normal now.

**Comment by jasonyihk** [comment]
tks.
